on: push
defaults:
  run:
    shell: bash
jobs:
  publish:
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]
    name: pack and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore
      - name: Clean
        run: |
          dotnet clean
          find . -name "*.nupkg" | xargs -I{} rm {}
      - name: Build (builds package)
        run: dotnet pack --configuration Release --no-restore
      - name: Push to nuget
        run: dotnet nuget push  "src/bin/Release/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate